@startuml

top to bottom direction
skinparam packageStyle rectangle

package "Decision" {

class DecisionInputSetDto {
  +workItems : DecisionInputWorkItemDto[]
  +repositories : RepoReferenceWithNameDto[]
}

class RepoReferenceWithNameDto {
  +repositoryName : string
}

class CommitInputDto {
  +commitId : string
  +tagBefore : string[]
  +tagAfter : string[]
  +exactTags : string[]
}

class DecisionInputWorkItemDto {
  +id : number
  +state : string
}

class DecisionAggregateResultDto {
  +doneWorkItems : DecisionInputWorkItemDto[]
  +otherWorkItems : DecisionInputWorkItemDto[]
}

class RepoBeforeAfterDto {
  +repositoryName : string
}

class CommitResultDto {
  +commitId : string
  +considerForPR : boolean
}

DecisionInputSetDto "1" --> "0..*" RepoReferenceWithNameDto : includes
RepoReferenceWithNameDto "1" --> "0..*" CommitInputDto : tracks
DecisionInputSetDto "1" --> "0..*" DecisionInputWorkItemDto : contains
DecisionAggregateResultDto "1" --> "0..*" RepoBeforeAfterDto : includes
RepoBeforeAfterDto "1" --> "0..*" CommitResultDto : includes

}


package "Sprint" {

class SprintDto {
  +id : string
  +name : string
  +path : string
  +url : string
}

class SprintAttributesDto {
  +startDate : string
  +finishDate : string
  +timeFrame : string
}

SprintDto "1" --> "1" SprintAttributesDto : contains

}


package "Work Item" {

class RelatedWorkItemsDataDto {
  +project : string
  +workItemId : number
  +relatedCount : number
  +visitedPullRequestIds : number[]
  +commitCount : number
}

class RelatedWorkItemsBatchDataDto {
  +project : string
  +requestedWorkItemIds : number[]
  +relatedCount : number
  +visitedPullRequestIds : number[]
  +commitCount : number
}

class WorkItemDto {
  +id : number
  +type : string
  +title : string
  +state : string
  +status : string
  +assignedTo : string
}

class WorkItemLinkDto {
  +type : string
  +targetId : string
  +url : string
  +isPR : boolean
  +prId : number
}

RelatedWorkItemsDataDto "1" --> "0..*" WorkItemDto : contains
RelatedWorkItemsBatchDataDto "1" --> "0..*" WorkItemDto : contains
WorkItemDto "1" --> "0..*" WorkItemLinkDto : references

}


package "Pull Request" {

class PullRequestSummaryDto {
  +prId : number
  +repositoryName : string
}

class WorkItemsDataDto {
  +prId : number
  +project : string
  +workItemCount : number
}

class WorkItemResultDto {
  +id : number
  +title : string
}

class LinkInfoDto {
  +prId : number
  +type : string
  +targetId : string
  +url : string
  +isPR : boolean
}

WorkItemsDataDto "1" --> "0..*" WorkItemResultDto : aggregates
WorkItemResultDto "1" --> "0..*" LinkInfoDto : references

}


package "Commit" {

class CommitTagContextDto {
  +exactTags : string[]
  +tagAfter : string[]
  +tagBefore : string[]
  +foundInBranch : boolean
}

class CommitsByPRDataDto {
  +prId : number
  +project : string
  +commitCount : number
}

class CommitsByWorkItemDataDto {
  +workItemId : number
  +project : string
  +commitCount : number
}

class CommitInfo {
  +commitId : string
  +repoName : string
}

CommitInfo "1" --> "0..1" CommitTagContextDto : hasContext
CommitsByPRDataDto "1" --> "0..*" CommitInfo : includes
CommitsByWorkItemDataDto "1" --> "0..*" CommitInfo : includes

}


' Cross-module relationships

RelatedWorkItemsDataDto "1" --> "0..*" PullRequestSummaryDto : references
RelatedWorkItemsBatchDataDto "1" --> "0..*" PullRequestSummaryDto : references

RelatedWorkItemsDataDto "1" --> "0..*" CommitInfo : aggregates
RelatedWorkItemsBatchDataDto "1" --> "0..*" CommitInfo : aggregates


@enduml